export default [
  {
    id: "ealhswith",
    name: "Ealhswith",
    episode: "S3.02",
    text: [
      "Young Ealhswith's fortunes have led her",
      "Down to Wessex, where Alfred's to wed her.",
      "But their wedding night",
      "Proves to be no delight",
      "As he'd rather get piles than bed her.",
    ],
  },
  {
    id: "aethelflaed-lady-of-the-mercians",
    name: "Æthelflæd, Lady of the Mercians",
    episode: "S3.03",
    text: [
      "If you think that women can't rule,",
      "Then Æthelflæd proves you're a fool.",
      "She led great campaigns,",
      "And defeated the Danes.",
      "She was just incomparably cool",
    ],
  },
  {
    id: "æfflæd",
    name: "Æfflæd",
    episode: "S3.04",
    text: [
      "For fans of tenth century sewing,",
      "The work of Queen Æfflæd's worth knowing:",
      "A scarf and arm wrap",
      "Worn by a dead chap,",
      "Displayed now in Durham - who's going?",
    ],
  },
  {
    id: "eadgifu",
    name: "Eadgifu",
    episode: "S3.05",
    text: [
      "Queen Eadgifu told Æthelstan,",
      '"You must never get married, young man."',
      "And through this device",
      "She became Queen Mum - twice -",
      "And Edgar the Peaceable's gran.",
    ],
  },
  {
    id: "ælfgifu-of-shaftesbury",
    name: "Ælfgifu of Shaftesbury",
    episode: "S3.06",
    text: [
      "In life she achieved little fame,",
      "But in death Ælfgifu's moment came,",
      "Her sainthood revealed",
      "When she magically healed",
      "The mad and the blind and the lame",
    ],
  },
  {
    id: "æthelflæd-of-damerham",
    name: "Æthelflæd of Damerham",
    episode: "S3.07",
    text: [
      "Æthelflæd got large holdings of land",
      "From her dad, who was wealthy and grand.",
      "She owned great estates",
      "(And some cups, bowls and plates).",
      "No wonder the king sought her hand!",
    ],
  },
  {
    id: "ælfgifu",
    name: "Ælfgifu",
    episode: "S3.08",
    text: [
      "Had a threesome (instead of her dinner).",
      'Dunstan yelled, "Ælfgifu, you\'re a sinner!"',
      "Sold abroad, then - it's said -",
      "His men chopped off her head,",
      "But she turned up alive - what a winner.",
    ],
  },
  {
    id: "æthelflæda",
    name: "Æthelflæda",
    episode: "S3.09a",
    text: [
      "She's known to us just as a breeder,",
      "The mother of England's brief leader",
      "Saint Edward the Martyr.",
      "She witnessed no charter",
      "- Æthelflæda Eneda/Candida",
    ],
  },
  {
    id: "wulfthryth",
    name: "Wulfthryth",
    episode: "S3.09b",
    text: [
      "As Wulfryth's devotions began",
      "She was seized by a lecherous man.",
      "She cried out, \"I'm a Nun,",
      "So you can't have your fun!\"",
      'He replied, "I\'m the king, so I can."',
    ],
  },
];
