export default [
  {
    id: "ealhswith",
    name: "Ealhswith",
    episode: "S3.02",
    text: [
      "Young Ealhswith's fortunes have led her",
      "Down to Wessex, where Alfred's to wed her.",
      "But their wedding night",
      "Proves to be no delight,",
      "As he'd rather get piles than bed her.",
    ],
  },
  {
    id: "aethelflaed,-lady-of-the-mercians",
    name: "Æthelflæd, Lady of the Mercians",
    episode: "S3.03",
    text: [
      "If you think that women can't rule,",
      "Then Æthelflæd proves you're a fool.",
      "She led great campaigns,",
      "And defeated the Danes.",
      "She was just incomparably cool.",
    ],
  },
  {
    id: "aelfflaed",
    name: "Ælfflæd",
    episode: "S3.04",
    text: [
      "For fans of tenth century sewing,",
      "The work of Queen Ælfflæd's worth knowing:",
      "A scarf and arm wrap",
      "Worn by a dead chap,",
      "Displayed now in Durham - who's going?",
    ],
  },
  {
    id: "eadgifu",
    name: "Eadgifu",
    episode: "S3.05",
    text: [
      "Queen Eadgifu told Æthelstan,",
      '"You must never get married, young man."',
      "And through this device",
      "She became Queen Mum - twice - ",
      "And Edgar the Peaceable's gran.",
    ],
  },
  {
    id: "aelfgifu-of-shaftesbury",
    name: "Ælfgifu of Shaftesbury",
    episode: "S3.06",
    text: [
      "In life she achieved little fame,",
      "But in death Ælfgifu's moment came,",
      "Her sainthood revealed",
      "When she magically healed",
      "The mad and the blind and the lame.",
    ],
  },
  {
    id: "aethelflaed-of-damerham",
    name: "Æthelflæd of Damerham",
    episode: "S3.07",
    text: [
      "Æthelflæd got large holdings of land",
      "From her dad, who was wealthy and grand.",
      "She owned great estates",
      "(And some cups, bowls and plates).",
      "No wonder the king sought her hand!",
    ],
  },
  {
    id: "aelfgifu",
    name: "Ælfgifu",
    episode: "S3.08",
    text: [
      "Had a threesome (instead of her dinner).",
      'Dunstan yelled, "Ælfgifu, you\'re a sinner!"',
      "Sold abroad, then - it's said -",
      "His men chopped off her head,",
      "But she turned up alive - what a winner.",
    ],
  },
  {
    id: "aethelflaeda-eneda/candida",
    name: "Æthelflæda Eneda/Candida",
    episode: "S3.09a",
    text: [
      "She's known to us just as a breeder,",
      "The mother of England's brief leader",
      "Saint Edward the Martyr.",
      "She witnessed no charter",
      "- Æthelflæda Eneda/Candida.",
    ],
  },
  {
    id: "wulfthyrth",
    name: "Wulfthyrth",
    episode: "S3.09b",
    text: [
      "As Wulfthryth's devotions began",
      "She was seized by a lecherous man.",
      "She cried out, \"I'm a nun,",
      "So you can't have your fun!\"",
      'He replied, "I\'m the king, so I can."',
    ],
  },
  {
    id: "aelfthryth",
    name: "Ælfthryth",
    episode: "S3.10",
    text: [
      "Ælfthryth, first queen of this land,",
      "Who Dunstan - that oaf - couldn't stand,",
      "Had looks that could stun.",
      "She ruled for her son,",
      "Once King Edward was slain.... by her hand?",
    ],
  },
  {
    id: "aelfgifu-of-york",
    name: "Ælfgifu of York",
    episode: "S3.11",
    text: [
      "Queen Ælfgifu's truly obscure.",
      "One person or two? We're not sure.",
      "King Æthelred's wife,",
      "Her achievement in life",
      "Was the number of children she bore.",
    ],
  },
  {
    id: "sigrid-the-haughty",
    name: "Sigrid the Haughty",
    episode: "S3.12",
    text: [
      "Though Sigrid and he were related,",
      "Harald thought he'd get rich if they dated.",
      "She just couldn't stand ",
      "How he asked for her hand,",
      "So she had the poor chap immolated.",
    ],
  },
  {
    id: "eladgyth",
    name: "Eladgyth",
    episode: "S3.13",
    text: [
      "Imprisoned, in times of great strife,",
      "When her husband had just lost his life,",
      "Ealdgyth needn't have feared,",
      "For Prince Edmund appeared,",
      "To free her and make her his wife.",
    ],
  },
  {
    id: "emma-of-normandy",
    name: "Emma of Normandy",
    episode: "S3.14",
    text: [
      "Queen Emma was scarily vexed,",
      "When her stepson said he'd be king next.",
      "Some setbacks occurred,",
      "But she had the last word,",
      "For she wrote the definitive text.",
    ],
  },
  {
    id: "aelfgifu-of-northampton",
    name: "Ælfgifu of Northampton",
    episode: "S3.15",
    text: [
      "Ælfgifu surpassed all expectations,",
      "In spite of some fearsome relations.",
      "She spent half her life",
      "As a second-best wife,",
      "Yet was regent of two different nations.",
    ],
  },
  {
    id: "edith-of-wessex",
    name: "Edith of Wessex",
    episode: "S3.16",
    text: [
      "When Queen Edith could not have a son,",
      "She was packed off to live as a nun.",
      "With her dad back in town",
      "She recovered her crown,",
      "And enjoyed stealing relics for fun!",
    ],
  },
  {
    id: "ealdgyth-of-mercia",
    name: "Ealdgyth of Mercia",
    episode: "S3.17",
    text: [
      "When he needed a Northern connection,",
      "Lady Ealdgyth was Harold's selection.",
      "This filled her with dread,",
      "For her first husband's head",
      "Was part of his trophy collection.",
    ],
  },
  {
    id: "matilda-of-flanders",
    name: "Matilda of Flanders",
    episode: "S3.18",
    text: [
      "Matilda, once spurned by a thegn,",
      "Chanced, years later, to meet him again.",
      "Now newly enthroned,",
      "She took all he owned,",
      "And it's rumoured she then had him slain.",
    ],
  },
  {
    id: "matilda-of-scotland",
    name: "Matilda of Scotland",
    episode: "S3.19",
    text: [
      "Matilda, from æthelings descended,",
      "Having proved that she'd never intended",
      "To live as a nun,",
      "Wed the Conqueror's son,",
      "And the two royal lines were thus blended.",
    ],
  },
  {
    id: "adeliza-of-louvain",
    name: "Adeliza of Louvain",
    episode: "S3.20",
    text: [
      "Adeliza, King Henry's young bride,",
      "Spent fifteen fruitless years by his side.",
      "Though he stopped his affairs,",
      "She gave him no heirs",
      "(But had seven kids after he'd died).",
    ],
  },
  {
    id: "matilda-of-boulogne",
    name: "Matilda of Boulogne",
    episode: "S3.21",
    text: [
      "With her fool of a husband in chains,",
      "Matilda took on his campaigns:",
      "Defeated his rival,",
      "Ensured his survival",
      "- She led with both courage and brains.",
    ],
  },
  {
    id: "eleanor-of-aquitaine",
    name: "Eleanor of Aquitaine",
    episode: "S3.22",
    text: [
      "Queen Eleanor, youth long since gone,",
      "Raised a ransom, fetched brides, battled on,",
      "Ruled England with poise,",
      "Filling in for her boys,",
      "Absent Richard and idiot John.",
    ],
  },
  {
    id: "berengaria-of-navarre",
    name: "Berengaria of Navarre",
    episode: "S3.24",
    text: [
      "King Richard wed young Berengaria,",
      "To win friends in the Aquitaine area.",
      "But Richard, she found,",
      "Was rarely around,",
      "Preferring his bedfellows hairier.",
    ],
  },
  {
    id: "isabella-of-angoulême",
    name: "Isabella of Angoulême",
    episode: "S3.25",
    text: [
      "Isabella, increasingly mad,",
      "Wed Hugh, which raised eyebrows a tad.",
      "By contract he oughta",
      "Have wed her young daughter,",
      "And she'd been betrothed to his dad.",
    ],
  },
  {
    id: "eleanor-of-provence",
    name: "Eleanor of Provence",
    episode: "S3.26",
    text: [
      "Queen Eleanor brought little joy",
      "To the English, whom she did annoy,",
      "By bagging rich brides,",
      "And the best jobs besides,",
      "For her numerous friends from Savoy.",
    ],
  },
  {
    id: "eleanor-of-castile",
    name: "Eleanor of Castile",
    episode: "S3.27",
    text: [
      "Poor Eleanor's whole life was spent",
      "Having babies wherever she went:",
      "In South Aquitaine,",
      "Palestine, on campaign,",
      "And North Wales, in a building site tent.",
    ],
  },
  {
    id: "margaret-of-france",
    name: "Margaret of France",
    episode: "S3.28",
    text: [
      "Queen Margaret rode north all the way",
      "To Stirling, but sighed with dismay,",
      "When she learned too late",
      'That her "romantic date"',
      "Was to see the king's new trebuchet.",
    ],
  },
  {
    id: "isabella-of-france",
    name: "Isabella of France",
    episode: "S3.29",
    text: [
      "Enraged by her husband's new beau,",
      'Isabella cried, "Edward must go!"',
      "She ended his reign,",
      "Then decreed he be slain,",
      "While in bed with his deadliest foe.",
    ],
  },
  {
    id: "philippa-of-hainault",
    name: "Philippa of Hainault",
    episode: "S3.31",
    text: [
      "Queen Philippa, on her white mare,",
      "Spoke in war to inspire and prepare",
      "The troops that she led",
      "- Or so Froissart said.",
      "In truth she was not even there.",
    ],
  },
  {
    id: "anne-of-bohemia",
    name: "Anne of Bohemia",
    episode: "S3.32",
    text: [
      "When you marry a princess well bred,",
      "Her large dowry should get you ahead.",
      "But when Richard wed Anne,",
      "He neglected to plan,",
      "And she cost him a fortune instead.",
    ],
  },
  {
    id: "isabella-of-valois",
    name: "Isabella of Valois",
    episode: "S3.33",
    text: [
      "Aged ten, with her first husband dead,",
      "Isabella was asked, would she wed",
      "The son of the louse",
      "Who had murdered her spouse?",
      'She replied, "Not a chance, dunderhead!"',
    ],
  },
  {
    id: "joan-of-navarre",
    name: "Joan of Navarre",
    episode: "S3.34",
    text: [
      "With nine kids, who were all minors still,",
      "Joan ruled as a regent until",
      "She bagged England's king,",
      "Gained a whole load of bling,",
      "And decided as queen to just chill.",
    ],
  },
  {
    id: "catherine-of-valois",
    name: "Catherine of Valois",
    episode: "S3.35",
    text: [
      "When her butler stripped off in the brine,",
      'Queen Catherine cried, "Isn\'t he fine!"',
      "The two were soon wed,",
      "And this later led",
      "To an unlikely new royal line.",
    ],
  },
  {
    id: "margaret-of-anjou",
    name: "Margaret of Anjou",
    episode: "S3.36",
    text: [
      "When her husband proved less use than none,",
      "Margaret set out to fight for her son.",
      "But when he was slain",
      "On Tewkesbury Plain",
      "Her two decades of work were undone.",
    ],
  },
  {
    id: "elizabeth-woodville",
    name: "Elizabeth Woodville",
    episode: "S3.38",
    text: [
      "Fair Elizabeth caught Edward's eye,",
      "And he hoped in his bed she'd soon lie.",
      "But she held him in check",
      "With a knife to her neck:",
      '"You must marry me, or I shall die!"',
    ],
  },
  {
    id: "anne-neville",
    name: "Anne Neville",
    episode: "S3.39",
    text: [
      "Did Anne hold her cousin’s love dear?",
      "Or was their romance insincere -  ",
      "Each seeking a route",
      "To a share of Mum’s loot?",
      "Her motives for marriage aren’t clear.",
    ],
  },
  {
    id: "elizabeth-of-york",
    name: "Elizabeth of York",
    episode: "S3.40",
    text: [
      "Elizabeth loved her young lad,",
      "Who greatly resembled her dad.",
      "She passed on her passion",
      "For jousts, dance and fashion, ",
      "But maybe she spoiled him a tad.",
    ],
  },
  {
    id: "katherine-of-aragon",
    name: "Katherine of Aragon",
    episode: "S3.41",
    text: [
      "Katherine bravely and skilfully fought",
      "When confronting her husband in court.",
      "He just couldn't cope,",
      "So he broke with the Pope ",
      "To obtain the divorce that he sought.",
    ],
  },
  {
    id: "anne-boleyn",
    name: "Anne Boleyn",
    episode: "S3.43",
    text: [
      "Anne wouldn’t join Henry in bed,",
      "Deciding to teach him instead",
      "That a wife can be dumped",
      "When your romance has slumped",
      "- A lesson that cost her her head.",
    ],
  },
  {
    id: "jane-seymour",
    name: "Jane Seymour",
    episode: "S3.46",
    text: [
      "The sources record that Queen Jane",
      "Was dull-witted, lowborn and quite plain.",
      "But with Henry she scored,",
      "For he had grown bored",
      "Of having a wife with a brain.",
    ],
  },
  {
    id: "anne-of-cleves",
    name: "Anne of Cleves",
    episode: "S3.47",
    text: [
      "When Henry, disguised, first met Anne,",
      "She thought him a boorish old man.",
      "He got offended,",
      "And this quickly ended",
      "Their romance before it began.",
    ],
  },
  {
    id: "katherine-howard",
    name: "Katherine Howard",
    episode: "S3.48",
    text: [
      "Young Katherine was fond of flirtation,",
      "Which led to her swift elevation.",
      "But having a fling",
      "Once she’d married the king",
      "Was a terminal miscalculation.",
    ],
  },
  {
    id: "katherine-parr",
    name: "Katherine Parr",
    episode: "S3.49",
    text: [
      "Though Katherine was really not keen,",
      "She accepted her fate - to be queen -",
      "To advance education,",
      "Aid church reformation,",
      "And bathe in warm milk to keep clean.",
    ],
  },
  {
    id: "philip-ii-of-spain",
    name: "Philip II of Spain",
    episode: "S3.50",
    text: [
      "Life in England for Philip was tough.",
      "Lacking power, he left in a huff,",
      "When he couldn't get crowned,",
      "And sadly had found",
      "That his wife never got up the duff.",
    ],
  },
  {
    id: "anne-of-denmark",
    name: "Anne of Denmark",
    episode: "S3.51",
    text: [
      "Anne loved music for lute, or a play,",
      "While James liked to hunt the whole day.",
      "Though he started to smell,",
      "They got on quite well,",
      "So long as he kept far away.",
    ],
  },
  {
    id: "henrietta-maria",
    name: "Henrietta Maria",
    episode: "S3.52",
    text: [
      "Henrietta in England was hated,",
      "As she spread Catholic faith, unabated.",
      "She provoked civil war,",
      "Then for an encore",
      "Helped her husband get decapitated.",
    ],
  },
  {
    id: "elizabeth-cromwell",
    name: "Elizabeth Cromwell",
    episode: "S3.53",
    text: [
      "Elizabeth thought when she wed,",
      "Rural life with her spouse lay ahead.",
      "Then he joined the army",
      "And she near went barmy,",
      "Stuck home with his mother instead.",
    ],
  },
  {
    id: "catherine-of-braganza",
    name: "Catherine of Braganza",
    episode: "S3.54",
    text: [
      "Charles's first date with Catherine fell flat.",
      "She was feeling too seasick to chat.",
      "Though pleasant and fair,",
      "The style of her hair",
      'Made Charles quip, "They\'ve brought me a bat!"',
    ],
  },
  {
    id: "mary-of-modena",
    name: "Mary of Modena",
    episode: "S3.55",
    text: [
      "Mary's foes said that she did deceive",
      "Forty folk, none of whom did perceive",
      "She'd used cushions for girth",
      "And faked giving birth",
      "- A fun story, but hard to believe.",
    ],
  },
  {
    id: "george-of-denmark",
    name: "George of Denmark",
    episode: "S3.56",
    text: [
      "George was lazy and dull, far from trim,",
      "Bad at English and possibly dim.",
      "An amenable man,",
      "He loved his wife Anne,",
      "And she was devoted to him.",
    ],
  },
  {
    id: "sophia-dorothea-of-celle",
    name: "Sophia Dorothea of Celle",
    episode: "S3.57",
    text: [
      "Prince George kept his wife, poor Sophia,",
      "Locked up, no one able to to see 'er.",
      "Her handsome young swain",
      "Was brutally slain,",
      "So he was unable to free 'er.",
    ],
  },
  {
    id: "caroline-of-ansbach",
    name: "Caroline of Ansbach",
    episode: "S3.58",
    text: [
      "King George thought that he was a wiz -",
      "His ideas and plans were the biz!",
      "But his every design",
      "Came from Queen Caroline,",
      "Who convinced him that her schemes were his.",
    ],
  },
  {
    id: "charlotte-of-mecklenburg-strelitz",
    name: "Charlotte of Mecklenburg-Strelitz",
    episode: "S3.59",
    text: [
      "George's wishlist and Charlotte aligned:",
      "She was pious, unworldly and kind.",
      "He cared not about looks",
      "If she'd read him good books",
      "And share games, so that he could unwind.",
    ],
  },
  {
    id: "caroline-of-brunswick",
    name: "Caroline of Brunswick",
    episode: "S3.60",
    text: [
      "George picked Caroline when broke and peeved.",
      "On their wedding night, both felt aggrieved:",
      "He was totally sloshed",
      "And she hadn't washed.",
      "Yet somehow an heir was conceived.",
    ],
  },
  {
    id: "adelaide-of-saxe-meiningen",
    name: "Adelaide of Saxe-Meiningen",
    episode: "S3.61",
    text: [
      'William begged Adelaide, "Please, be mine."',
      "Twice her age, and a father of nine,",
      "He swore lots, loved to bet,",
      "And was deeply in debt.",
      "Yet they wed, and they got on just fine.",
    ],
  },
  {
    id: "prince-albert",
    name: "Prince Albert",
    episode: "S3.62",
    text: [
      "People said Albert's Great Exhibition",
      "Would cause bankruptcy, plague and sedition.",
      "But this hard-working man",
      "Made it all go to plan,",
      "And a surplus was raised in addition.",
    ],
  },
  {
    id: "alexandra-of-denmark",
    name: "Alexandra of Denmark",
    episode: "S3.64",
    text: [
      "Bertie found German ladies a fright: ",
      "Too boring, too plain, too uptight. ",
      "So he widened his net, ",
      "And, from Denmark, he met",
      "Princess Alix, and she was Just Right.",
    ],
  },
  {
    id: "mary-of-teck",
    name: "Mary of Teck",
    episode: "S3.65",
    text: [
      "George was dull, Mary shy; when he met her,",
      "Their chats could have gone a lot better.",
      "For a true heart to heart",
      "They must needs be apart,",
      "And express all their feelings by letter.",
    ],
  },
  {
    id: "wallis-simpson",
    name: "Wallis Simpson",
    episode: "S3.66",
    text: [
      "With his heart set on Wallis alone, ",
      "King Edward surrendered his throne. ",
      "This left her without",
      "Any chance to back out; ",
      "Whether she loved him too is unknown.",
    ],
  },
  {
    id: "elizabeth-bowes-lyon",
    name: "Elizabeth Bowes-Lyon",
    episode: "S3.68",
    text: [
      "Elizabeth's day would begin",
      "With a glass of Dubonnet and gin,",
      "Then a quick claret fix,",
      "Martinis at six,",
      "And round off with champagne for the win.",
    ],
  },
  {
    id: "prince-philip",
    name: "Prince Philip",
    episode: "S3.70",
    text: [
      "Philip fostered the latest technology,",
      "Had a passion for sport and ecology,",
      "A fine naval career,",
      "But is known best, I fear,",
      "For his talent for dontopedalogy.",
    ],
  },
];
